# Generated by Django 4.1.5 on 2023-01-03 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(null=True, related_name='assignee_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_tasks',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_tasks',
                                    to='tasks.status'),
        ),
        migrations.AddField(
            model_name='picture',
            name='task',
            field=models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, related_name='images',
                                    to='tasks.task'),
        ),
    ]
