# Generated by Django 4.1.5 on 2023-01-05 19:23

from django.db import migrations


def create_base_statuses(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Status = apps.get_model('tasks', 'Status')
    new_status = Status.objects.create(name="New", visibility=False)
    in_work_status = Status.objects.create(name="In work", visibility=True)
    done_status = Status.objects.create(name="Done", visibility=False)


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_base_statuses),
    ]
