version: '3.9'

services:
  web:
    container_name: todo_app-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db
  #      - redis

  db:
    image: postgres
    container_name: todo_app-db
    volumes:
      - todo_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=todoapp
      - POSTGRES_USER=todoapp
      - POSTGRES_PASSWORD=todoapp
    ports:
      - "5432:5432"

#  redis:
#    container_name: todoapp-redis
#    image: redis:alpine
#  celery:
#    container_name: todoapp-celery
#    build: .
#    command: celery -A core worker -l info
#    volumes:
#      - .:/code
#    depends_on:
#      - redis
#  celery-beat:
#    build: .
#    command: celery -A core beat -l info
#    volumes:
#      - .:/code
#    depends_on:
#      - redis

volumes:
  todo_db:
    external: false